/*
 * FenetreScore.java                     30/11/2015
 * Licence PRO RTAI
 */
package vue;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Classe correspondant à la vue pour l'affichage du score
 * @author Audélia Bertaina & Alicia Masmayoux
 */
public class FenetreScore extends javax.swing.JDialog {

    /** Image contenant les émoticonnes pour l'affichage des scores */
    private static final ImageIcon SMILE = new ImageIcon("./src/imgs/smile.png");
    private static final ImageIcon NEUTRE = new ImageIcon("./src/imgs/neutre.png");
    private static final ImageIcon SAD = new ImageIcon("./src/imgs/sad.png");
          
    /** Fentre Correspondant au Jeu */
    private FenetreJeu frameParent;

    /**
     * Constructeur par défaut
     * @param frameJeu la fenetre du jeu de la partie en cours
     * @param modal pour savoir si la fenetre est modale ou pas
     * @param score le score de la partie en cours
     * @param nbSouris le nombre de souris au départ
     */
    public FenetreScore(FenetreJeu frameJeu, boolean modal, int score, int nbSouris) {
        frameParent = frameJeu;
        
        int morte = nbSouris-score;
        int sauve = score;

        initComponents();
        this.setTitle("Jeu Chats et Souris - Score");
        
        if(morte == 0){
            labEmo.setIcon(SMILE);
            txtScore.setText("<html>Vous avez réussi à sauver les " + 
                    String.valueOf(sauve) + "<br> souris présente au départ !!</html>");
            txtScore.setHorizontalAlignment(JLabel.CENTER);
        }else if(sauve == 0){
            labEmo.setIcon(SAD);
            txtScore.setText("<html>Vous n'avez réussi à sauvez aucune des " + 
                     String.valueOf(morte) + "<br> souris présente au départ.</html>");
            txtScore.setHorizontalAlignment(JLabel.CENTER);
        }else{
            labEmo.setIcon(NEUTRE);
            txtScore.setText("<html>Vous avez réussi à sauver : " 
                    + String.valueOf(sauve) + "<br> souris et " 
                    + String.valueOf(morte) + " ont été mangées\n par des chats.</html>");
            txtScore.setHorizontalAlignment(JLabel.CENTER);
        }
        
        //Action à la fermeture de la fenêtre
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                frameJeu.dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauFond = new javax.swing.JPanel();
        txtScore = new javax.swing.JLabel();
        btnRejouer = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        labEmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panneauFond.setBackground(new java.awt.Color(75, 80, 84));
        panneauFond.setForeground(new java.awt.Color(255, 255, 255));

        txtScore.setForeground(new java.awt.Color(255, 255, 255));
        txtScore.setText("Message");
        txtScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnRejouer.setText("Rejouer");
        btnRejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejouerActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauFondLayout = new javax.swing.GroupLayout(panneauFond);
        panneauFond.setLayout(panneauFondLayout);
        panneauFondLayout.setHorizontalGroup(
            panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauFondLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createSequentialGroup()
                        .addComponent(labEmo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRejouer, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panneauFondLayout.setVerticalGroup(
            panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauFondLayout.createSequentialGroup()
                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtScore)
                        .addGap(50, 50, 50))
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labEmo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnRejouer))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauFond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        frameParent.dispose();
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejouerActionPerformed
        frameParent.dispose();
        //TODO
        this.dispose();
    }//GEN-LAST:event_btnRejouerActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRejouer;
    private javax.swing.JLabel labEmo;
    private javax.swing.JPanel panneauFond;
    private javax.swing.JLabel txtScore;
    // End of variables declaration//GEN-END:variables
}
