/*
 * FenetreEditerNext.java                     30/11/2015
 * Licence PRO RTAI
 */
package vue;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modele.Animal;
import modele.CasePossible;
import modele.Plateau;

/**
 * Classe permettant de représenter la deuxième vue pour l'éditeur de niveau
 * @author Audélia Bertaina & Alicia Masmayoux
 */
public class FenetreEditerNext extends javax.swing.JFrame {

    /** Définition de l'image de fond **/
    private final Image mainBackgroundImage = new ImageIcon(getClass().
                  getResource("/background.png")).getImage();
    
    private Plateau unPlateau;
    
    /** Définit tous les éléments présent sur le plateau */
    private final ImageIcon VIDE = new ImageIcon(getClass().getResource("/imgs/vide.png"));
    private final ImageIcon IN = new ImageIcon(getClass().getResource("/imgs/in.png"));
    private final ImageIcon OUT = new ImageIcon(getClass().getResource("/imgs/out.png"));
    private final ImageIcon CHAT = new ImageIcon(getClass().getResource("/imgs/chat.png"));
    private final ImageIcon SOURIS = new ImageIcon(getClass().getResource("/imgs/souris.png"));
    private final ImageIcon TELPORTEUR = new ImageIcon(getClass().getResource("/imgs/teleporteur.png"));
    private final ImageIcon MUR = new ImageIcon(getClass().getResource("/imgs/mur.png"));
    private final ImageIcon ICON = new ImageIcon(getClass().getResource("/imgs/icon.png"));
    private final ImageIcon ICONHOVER = new ImageIcon(getClass().getResource("/imgs/iconHover.png"));
    
    /** Définition du plateau de jeu */
    JLabel[][] jboard;
    
    /**
     * Constructeur par défaut
     */
    public FenetreEditerNext(Plateau plateau) {
        unPlateau = plateau;
        initComponents();
        definitionAffichage();
    }
    
    /**
     * Définit l'affichage de la fenêtre courante
     */
    public final void definitionAffichage(){
        //Bouton représenté par l'icon de l'application permettant 
        //de revenir au menu principal
        FenetreEditerNext currentFrame = this;
        HoverButton btnIcon = new HoverButton(ICON, ICONHOVER);
        panneauIcon.add(btnIcon);
        panneauIcon.revalidate();
        panneauIcon.repaint();
        
        btnIcon.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    currentFrame.dispose();
                }
        });

        //Ajoute le nombre de souris dans la comboBox 
        for(int i = 1; i <= unPlateau.getNbCasesVides()/2; i++){
            comboSouris.addItem(i);
        }
 
        //Création des bouton radio avec les flêche les souris et les téléporteur
        ImageIcon up = new ImageIcon(getClass().getResource("/imgs/up_detoure.png"));
        ImageIcon down = new ImageIcon(getClass().getResource("/imgs/down_detoure.png"));
        ImageIcon left = new ImageIcon(getClass().getResource("/imgs/left_detoure.png"));
        ImageIcon right = new ImageIcon(getClass().getResource("/imgs/right_detoure.png"));
        ImageIcon souris = new ImageIcon(getClass().getResource("/imgs/souris_detoure.png"));
        ImageIcon teleporteur = new ImageIcon(getClass().getResource("/imgs/teleporteur_detoure.png"));
            
        //Affiche les images pour les bouton radio
        iconUp.setIcon(up);
        iconDown.setIcon(down);
        iconLeft.setIcon(left);
        iconRight.setIcon(right);
        iconSouris.setIcon(souris);
        iconTeleporteur.setIcon(teleporteur);

        //Définition de la grille de jeu
        jboard = new JLabel[Plateau.NB_COLONNES][Plateau.NB_LIGNES];
        
        for(int j = 0; j < Plateau.NB_LIGNES; j++){
            for(int i = 0; i < Plateau.NB_COLONNES; i++){

                jboard[i][j] = new JLabel(MUR);

                //Récupère le type de case de la case de coordoné i, j
                CasePossible caseP = unPlateau.getLesCases()[i][j].getTypeCase();
                
                //Affiche toute les case du plateau définit précédément
                jboard[i][j] = new JLabel(caseP == CasePossible.ENTREE ? IN :
                                          caseP == CasePossible.SORTIE ? OUT :
                                          caseP == CasePossible.VIDE ? VIDE : MUR);
                
                //Affiche dans la grille du jeu la grille précédente
                grilleJeu.add(jboard[i][j]);
            }
        }
        
        // Parcours la liste des chats pour les afficher
        for(Animal a : unPlateau.getLesChats()) {
            jboard[a.getPositionX()][a.getPositionY()].setIcon(CHAT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauFond = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(mainBackgroundImage, 0, 0, null);
            }
        };
        grilleJeu = new javax.swing.JPanel();
        panneauIcon = new javax.swing.JPanel();
        btnCreer = new javax.swing.JButton();
        iconUp = new javax.swing.JLabel();
        labUp = new javax.swing.JLabel();
        comboUp = new javax.swing.JComboBox();
        comboRight = new javax.swing.JComboBox();
        labRight = new javax.swing.JLabel();
        iconRight = new javax.swing.JLabel();
        iconDown = new javax.swing.JLabel();
        labDown = new javax.swing.JLabel();
        comboDown = new javax.swing.JComboBox();
        comboLeft = new javax.swing.JComboBox();
        labLeft = new javax.swing.JLabel();
        labSouris = new javax.swing.JLabel();
        iconTeleporteur = new javax.swing.JLabel();
        iconLeft = new javax.swing.JLabel();
        comboTeleporteur = new javax.swing.JComboBox();
        comboSouris = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        iconSouris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        grilleJeu.setBackground(new java.awt.Color(52, 55, 58));
        grilleJeu.setBorder(null);
        grilleJeu.setLayout(new java.awt.GridLayout(6, 8));

        panneauIcon.setOpaque(false);
        panneauIcon.setLayout(new java.awt.GridLayout(1, 0));

        btnCreer.setText("Créer Niveau");
        btnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerActionPerformed(evt);
            }
        });

        labUp.setForeground(new java.awt.Color(255, 255, 255));
        labUp.setText("Haut");

        comboUp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboRight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        labRight.setForeground(new java.awt.Color(255, 255, 255));
        labRight.setText("Droite");

        labDown.setForeground(new java.awt.Color(255, 255, 255));
        labDown.setText("Bas");

        comboDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboLeft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        labLeft.setForeground(new java.awt.Color(255, 255, 255));
        labLeft.setText("Gauche");

        labSouris.setForeground(new java.awt.Color(255, 255, 255));
        labSouris.setText("Souris");

        comboTeleporteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "2", "3", "4" }));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Téléporteur");

        javax.swing.GroupLayout panneauFondLayout = new javax.swing.GroupLayout(panneauFond);
        panneauFond.setLayout(panneauFondLayout);
        panneauFondLayout.setHorizontalGroup(
            panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauFondLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createSequentialGroup()
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneauFondLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createSequentialGroup()
                                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(iconTeleporteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iconLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iconSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboTeleporteur, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createSequentialGroup()
                                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(iconDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iconRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iconUp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panneauFondLayout.createSequentialGroup()
                                                .addComponent(labDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboDown, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panneauFondLayout.createSequentialGroup()
                                                .addComponent(labRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboRight, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panneauFondLayout.createSequentialGroup()
                                                .addComponent(labUp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboUp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(btnCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(grilleJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addComponent(panneauIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panneauFondLayout.setVerticalGroup(
            panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panneauIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(grilleJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panneauFondLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iconUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconRight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labRight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconDown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labDown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboLeft)))
                        .addGap(16, 16, 16)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboSouris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iconSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboTeleporteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(iconTeleporteur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnCreer)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerActionPerformed
        //Définit le nombre de flêches et de téléporteur a utiliser pour le niveau
        unPlateau.setNbFlechesBas(Integer.parseInt(comboDown.getSelectedItem().toString()));
        unPlateau.setNbFlechesHaut(Integer.parseInt(comboUp.getSelectedItem().toString()));
        unPlateau.setNbFlechesDroite(Integer.parseInt(comboRight.getSelectedItem().toString()));
        unPlateau.setNbFlechesGauche(Integer.parseInt(comboLeft.getSelectedItem().toString()));
        unPlateau.setNbTeleporteurs(Integer.parseInt(comboTeleporteur.getSelectedItem().toString()));
        unPlateau.setNbSouris(Integer.parseInt(comboSouris.getSelectedItem().toString()));

        Start.addPlateau(unPlateau);
        this.dispose();
    }//GEN-LAST:event_btnCreerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreer;
    private javax.swing.JComboBox comboDown;
    private javax.swing.JComboBox comboLeft;
    private javax.swing.JComboBox comboRight;
    private javax.swing.JComboBox comboSouris;
    private javax.swing.JComboBox comboTeleporteur;
    private javax.swing.JComboBox comboUp;
    private javax.swing.JPanel grilleJeu;
    private javax.swing.JLabel iconDown;
    private javax.swing.JLabel iconLeft;
    private javax.swing.JLabel iconRight;
    private javax.swing.JLabel iconSouris;
    private javax.swing.JLabel iconTeleporteur;
    private javax.swing.JLabel iconUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labDown;
    private javax.swing.JLabel labLeft;
    private javax.swing.JLabel labRight;
    private javax.swing.JLabel labSouris;
    private javax.swing.JLabel labUp;
    private javax.swing.JPanel panneauFond;
    private javax.swing.JPanel panneauIcon;
    // End of variables declaration//GEN-END:variables
}
